services:
  # app:
  #   build: ./backend
  #   container_name: app
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - mongo
  #     - psql
  #   volumes:
  #     - ./backend:/app
  #   command: npm run start:dev
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"
  #   networks:
  #     - app-network

  # mongo:
  #   image: mongo:latest
  #   container_name: db_mongo
  #   logging:
  #     driver: "none"
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - app-network

  # psql:
  #   container_name: db_psql
  #   image: postgres:13
  #   restart: always
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - psql_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # mongosh:
  #   image: mongo:latest
  #   container_name: mongo_shell
  #   command: ["sleep", "infinity"]
  #   networks:
  #     - app-network
  #   depends_on:
  #     - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    # env_file:
    #   - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

# volumes:
#   mongo_data: {}
#   psql_data: {}

networks:
  app-network:
